# Generated by Django 2.2.6 on 2019-11-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_indicator', models.BooleanField(default=False)),
                ('client_deposit', models.BooleanField(default=False)),
                ('date_enroller', models.DateField(auto_now_add=True)),
                ('date_terminate', models.DateField()),
            ],
            options={
                'verbose_name': 'Client account',
                'verbose_name_plural': 'Client accounts',
            },
        ),
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dough_description', models.CharField(max_length=50)),
                ('dough_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('name_of_your_order', models.CharField(max_length=200)),
                ('price_order', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.Order')),
            ],
            options={
                'verbose_name': 'Ordered toppings',
                'verbose_name_plural': 'Ordered toppings',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snack_description', models.CharField(max_length=50)),
                ('snack_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Snacks',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_description', models.CharField(max_length=50)),
                ('topping_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_description', models.CharField(max_length=200)),
                ('dough_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.Dough')),
                ('order_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.Order')),
                ('ordered_toppings_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.OrderedToppings')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('order_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.Order')),
            ],
            options={
                'verbose_name': 'Ordered payment',
                'verbose_name_plural': 'Ordered payments',
            },
        ),
        migrations.AddField(
            model_name='orderedtoppings',
            name='topping_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.Topping'),
        ),
        migrations.CreateModel(
            name='OrderedSnacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.Order')),
                ('snack_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.Snacks')),
            ],
            options={
                'verbose_name': 'Ordered snacks',
                'verbose_name_plural': 'Ordered snacks',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_tax_id', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee_job_category', models.CharField(max_length=100)),
                ('person_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('sales_tax', models.FloatField(default=0.05)),
                ('client_account_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.ClientAccount')),
                ('employee_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.Employee')),
            ],
            options={
                'verbose_name': 'Client transaction',
                'verbose_name_plural': 'Client transactions',
            },
        ),
        migrations.CreateModel(
            name='ClientAccountPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_account_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.ClientAccount')),
                ('person_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dj_pizzas.Person')),
            ],
            options={
                'verbose_name': 'Client account person',
                'verbose_name_plural': 'Client accounts persons',
            },
        ),
    ]
