# Generated by Django 2.2.7 on 2019-11-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(related_name='order_template', to='dj_pizzas.InstancePizza'),
        ),
    ]
