# Generated by Django 2.2.7 on 2019-11-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancepizza',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizza_template', to='dj_pizzas.Pizza'),
        ),
    ]
