# Generated by Django 2.2.7 on 2019-12-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='46cee5685b3d4a0e838e6dd66887e0896d7061e3cf264ecdac7b783e958d78d3', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='a0f371e1f11a407cade58bb74eb2ddd3935fe771fd10430f8a8b630c36b8a50f', max_length=300, null=True),
        ),
    ]
