# Generated by Django 2.2.7 on 2019-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='1abf4e299c104f85902705106d73d00363da1e18b37645348ef5f51bfd4da6ce', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='2e45fe9edd434a8ca3c82b9d0db3125e0e225be6777140878b720302507e91a9', max_length=300, null=True),
        ),
    ]
