# Generated by Django 2.2.7 on 2019-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='4fc3968ddd104158863d52b24d9b7880e4bd8f75d54e4ae19d9a66feccc96895', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='c4e7ab5054c04f40ba604145da76a1f3ed4b955d3fdb43d1a8fffe8b8cb6f30d', max_length=300, null=True),
        ),
    ]
