# Generated by Django 2.2.7 on 2019-11-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='e4952d43338f4af78ec9f7ba01a78804118ea7471b5247ecb660783751f3b9c8', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='051a3bfd12654fde96f9faaf730815fff1bde753249a42e8901cf1992dba22de', max_length=300, null=True),
        ),
    ]
